name: Schema Validation
on: [push]

jobs:
  build:
    name: Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: list workspace
        run: 'ls -la $GITHUB_WORKSPACE'
      - name: Install SDKMAN
        run: 'bash $GITHUB_WORKSPACE/setupenv.sh'